apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensorhub-nginx-deployment
  name: sensorhub-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensorhub-nginx-deployment
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sensorhub-nginx-deployment
        deploymentconfig: sensorhub-nginx-deployment
    spec:
      containers:
      - image: docker.io/mioja/sensorhub-nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: HOSTNAME
          value: sensorhub-test-pwp-deploy-tests.2.rahtiapp.fi
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: docker.io/mioja/sensorhub:latest
        imagePullPolicy: Always
        name: sensorhub
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 1500m
            memory: 7Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
