apiVersion: v1
kind: Service
metadata:
  labels:
    app: sensorhub-nginx-deployment
  name: sensorhub-nginx-deployment
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sensorhub-nginx-deployment
    deploymentconfig: sensorhub-nginx-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
